spring:
  datasource:
    url: jdbc:postgresql://db:5432/calendar
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html