spring:
  datasource:
    url: jdbc:postgresql://db:5432/calendar
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html